name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://www.richolaniyan.com --delete --exclude ".git/*" --exclude ".github/*" --exclude ".gitignore" --exclude "README.md" --exclude ".DS_Store" --exclude ".gitmodules"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2HEP4SVRRW6KZ --paths "/*"
